# -*- coding: utf-8 -*-
r"""矩陣單元 · 單一來源內容。

富文字語法：
  行內數學 \( ... \)   顯示數學 \[ ... \]   粗體 **...**   挖空 【答案】
挖空只在「重點與公式」使用（學生版會挖空、教師版顯示紅字答案）。

※ 本檔目前含 Part 0＋考點 1、2 與代表性 Part 2／3（驗證流程用）；
   考點 3–5 與完整 Part 2／3 待補。
"""

UNIT = {
    "slug": "matrix",
    "file": "115學測數學_矩陣_互動學習.html",
    "page_title": "115 學測數學 · 矩陣 · 互動學習",
    "emoji": "🧮",
    "title": "矩陣",
    "exam_tag": "115 學測",
    "hero_sub": "Part 1 五大考點 ｜ Part 2 模擬實戰 ｜ Part 3 考前速查",
    "hero_sub2": "每個考點皆含：重點與公式 · 常見誤解 · 歷屆試題 · 解題策略",
    "part1_label": "五大考點",
    "foot": "115 學測數學 · 矩陣互動學習講義　|　點按鈕逐題核對，先想再看答案效果最好。",

    "part0": {
        "heading": "為什麼矩陣是穩拿分的單元",
        "trend_table": {
            "years": [106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
            "counts": ["0.5", "1.0", "1.0", "1.0", "1.25", "1.0", "2.0", "1.5", "2.0", "1.0"],
            "total": "12.25",
        },
        "notes": [
            r"**幾乎年年都考、難度偏易～中**：是穩穩拿分的單元，112、114 年各約 2 題為近年高點。",
            r"命題集中在兩大主軸：**三元一次聯立（高斯消去）** 與 **平面線性變換（旋轉／鏡射、面積與行列式）**，皆為 ★★★ 必考核心。",
            r"**最愛跨單元整合**：與機率（\(113\) 多11 係數由骰子硬幣決定）、數列（\(115\) 多8 矩陣冪分量遞迴）、空間（\(114\) 選14、\(115\) 單5）、向量與三角（\(114\) 混18–20 旋轉題組）結合。",
            r"**混合題組（手寫 18–20）** 幾乎每年以「旋轉矩陣＋向量＋三角」整合呈現，是高分群的分水嶺，務必練手寫表達。",
        ],
        "map": r"五大考點依學習脈絡：① 意義、相等與乘法 → ② 高次方（降冪、凱萊–漢米頓）→ ③ 反方陣與解矩陣方程 → ④ 一次聯立與高斯消去（**★★★**）→ ⑤ 平面線性變換（**★★★**）。前三點是地基、後兩點是主戰場。",
    },

    "kps": [
        {
            "num": "考點 1", "id": "kp1", "nav": "意義、相等與乘法",
            "title": r"矩陣的意義、相等與乘法",
            "intro": r"矩陣就是把一堆數「排成長方陣」一起處理。這個考點是後面所有運算的地基——先弄懂**怎麼描述一個矩陣（階、第幾列第幾行）、兩矩陣何時相等、乘法到底怎麼乘**。學測幾乎不單獨考定義，而是把「相等」與「乘法」綁在一起，要你**對應位置列出聯立方程式**求未知數。",
            "points": [
                {"label": r"階與元素", "lines": [
                    r"有 \(m\) 列、\(n\) 行的矩陣稱為 【\(m\times n\)】 階；",
                    r"列數＝行數（同為 \(n\)）的矩陣稱 【方陣】；",
                    r"以 \(a_{ij}\) 表示第 【\(i\)】 列第 【\(j\)】 行的元，整個矩陣簡記 \(A=[a_{ij}]_{m\times n}\)（[[列在前、行在後||「列」是橫的、「行」是直的。\(a_{23}\) 指第 2 橫列、第 3 直行那一格，順序千萬別顛倒。]]）。"]},
                {"label": r"矩陣相等", "lines": [
                    r"兩矩陣相等 \(\Leftrightarrow\) 同階，且 【對應位置的元全部相等】；",
                    r"所以一個矩陣等式 ＝ 把對應位置一一列成聯立方程式——這是本考點最核心的動作。"]},
                {"label": r"加減與係數積", "lines": [
                    r"只有 【同階】 矩陣能相加減，做法是對應位置各自加減；",
                    r"\(kA\) 是把 \(A\) 的 【每一個元】 都乘以 \(k\)；",
                    r"行列式對照：\(n\) 階方陣 \(A\) 有 \(\det(kA)=\) 【\(k^{\,n}\det A\)】（[[和「矩陣乘 k」不一樣||矩陣乘 k 是「每個元」都乘 k；但行列式的性質是「某一列（或一行）」乘 k，行列式才乘 k。n 階方陣每一列都被乘了 k，行列式就多出 \(k^n\) 倍。]]）。"]},
                {"label": r"零矩陣 \(O\) 與單位方陣 \(I\)", "lines": [
                    r"單位方陣 \(I_2=\begin{bmatrix}1&0\\0&1\end{bmatrix}\)（對角線為 1、其餘為 0）；",
                    r"它是乘法的「1」：任意方陣皆 【\(IA=AI=A\)】；",
                    r"零矩陣 \(O\) 是加法的「0」，例如 \(O_2=\begin{bmatrix}0&0\\0&0\end{bmatrix}\)。"]},
                {"label": r"矩陣乘法", "lines": [
                    r"\(A_{m\times n}B_{n\times p}=C_{m\times p}\)，可乘條件是 [[前者行數＝後者列數||中間的 \(n\) 要相同才能乘；乘完後外圍的 \(m\times p\) 就是答案的階。「前行＝後列」記這四個字。]]；",
                    r"乘積第 \(i\) 列 \(j\) 行的元 \(c_{ij}=\)（【\(A\) 第 \(i\) 列】）與（【\(B\) 第 \(j\) 行】）對應相乘再相加；",
                    r"口訣：**[[左列右行內積||拿左矩陣的「一整列」去和右矩陣的「一整行」逐項相乘再相加，就是那一格的值。]]**；",
                    r"二階具體算法：\(\begin{bmatrix}a&b\\c&d\end{bmatrix}\begin{bmatrix}p&q\\r&s\end{bmatrix}=\begin{bmatrix}ap+br&aq+bs\\cp+dr&cq+ds\end{bmatrix}\)。"]},
                {"label": r"性質與三大陷阱", "lines": [
                    r"有結合律 \((AB)C=A(BC)\)、分配律 \(A(B+C)=AB+AC\)，但 **沒有交換律**，一般 【\(AB\neq BA\)】，由此衍生三個常錯：",
                    r"① \(AB=O\) 【不一定】 有 \(A=O\) 或 \(B=O\)（矩陣有 [[零因子||例如 \(\begin{bmatrix}0&1\\0&0\end{bmatrix}\) 自乘就得零矩陣，但它本身不是零矩陣。這在實數絕不會發生，是矩陣特有的陷阱。]]）；",
                    r"② \(AB=AC\) 【不一定】 有 \(B=C\)（要 \(A\) 可逆才能左消去）；",
                    r"③ 乘法公式失效：\((A+B)^2=\) 【\(A^2+AB+BA+B^2\)】，**不可**寫成 \(A^2+2AB+B^2\)（除非剛好 \(AB=BA\)）。"]},
            ],
            "misconceptions": [
                {"wrong": r"\(a_{ij}\) 是第 \(i\) 行第 \(j\) 列", "right": r"是第 \(i\) 列第 \(j\) 行（列在前）"},
                {"wrong": r"任意兩矩陣都能相乘", "right": r"須「前矩陣行數＝後矩陣列數」才可乘"},
                {"wrong": r"\(AB=BA\)", "right": r"一般 \(AB\neq BA\)，矩陣乘法**不交換**"},
                {"wrong": r"\(AB=O\Rightarrow A=O\) 或 \(B=O\)", "right": r"不一定！矩陣可有「零因子」"},
                {"wrong": r"\(AB=AC\Rightarrow B=C\)", "right": r"須 \(A\) 可逆才能左消去"},
            ],
            "questions": [
                {"tag": "108 舊制 · 選填 A", "level": "★☆☆（易）", "core": "矩陣的相等、矩陣的乘法",
                 "body": r"設 \(x,y\) 為實數，且滿足 \(\begin{bmatrix}3&-1&3\\2&4&-1\end{bmatrix}\begin{bmatrix}x\\y\\1\end{bmatrix}=\begin{bmatrix}6\\-6\end{bmatrix}\)，則 \(x+3y=\) ？",
                 "solution": {"brief": r"\(x+3y=-4\)",
                              "steps": [r"依乘法定義得 \(\begin{cases}3x-y+3=6\\2x+4y-1=-6\end{cases}\Rightarrow\begin{cases}3x-y=3\\2x+4y=-5\end{cases}\)，解得 \(x=\tfrac12,\;y=-\tfrac32\)，故 \(x+3y=\tfrac12-\tfrac92=-4\)。"]}},
                {"tag": "107 舊制 · 選填 F", "level": "★★☆（中）", "core": "矩陣的乘法定義",
                 "body": r"設 \(a,b,c,d,e,x,y,z\) 皆為實數，考慮矩陣相乘 \(\begin{bmatrix}a&b\\c&d\\1&2\end{bmatrix}\begin{bmatrix}-3&5&7\\-4&6&e\end{bmatrix}=\begin{bmatrix}3&x&7\\0&y&7\\-11&z&23\end{bmatrix}\)，則 \(y=\) ？（化成最簡分數）",
                 "solution": {"brief": r"\(y=\dfrac72\)",
                              "steps": [r"由第三列定 \(e\)：\(1\cdot7+2e=23\Rightarrow e=8\)。由第二列：\(-3c-4d=0\) 且 \(7c+de=7\Rightarrow 7c+8d=7\)，解得 \(c=7,\;d=-\tfrac{21}{4}\)，故 \(y=5c+6d=35-\tfrac{126}{4}=\tfrac72\)。"]}},
                {"tag": "112 數B · 單選 2", "level": "★☆☆（易）", "core": "矩陣的乘法",
                 "body": r"考慮實數二階方陣 \(\begin{bmatrix}a&b\\c&d\end{bmatrix}\)，若 \(\begin{bmatrix}0&1\\1&0\end{bmatrix}\begin{bmatrix}a&b\\c&d\end{bmatrix}\begin{bmatrix}1&0\\0&-2\end{bmatrix}=\begin{bmatrix}3&-4\\-9&-7\end{bmatrix}\)，則 \(c-2b\) 之值為何？",
                 "options": [r"\(-11\)", r"\(-4\)", r"\(1\)", r"\(10\)", r"\(11\)"],
                 "solution": {"brief": r"(2)，\(c-2b=-4\)",
                              "steps": [r"左乘 \(\begin{bmatrix}0&1\\1&0\end{bmatrix}\) 是把上下兩列對調、右乘 \(\begin{bmatrix}1&0\\0&-2\end{bmatrix}\) 是把第二行乘 \(-2\)，得 \(\begin{bmatrix}c&-2d\\a&-2b\end{bmatrix}=\begin{bmatrix}3&-4\\-9&-7\end{bmatrix}\)，故 \(c=3,\;-2b=-7\)，得 \(c-2b=-4\)。"]}},
                {"tag": "113 數B · 選填 13", "level": "★☆☆（易）", "core": "矩陣的乘法",
                 "body": r"已知 \(a,b,c,d\) 為實數，且 \(\begin{bmatrix}1&-1\\3&-2\end{bmatrix}\begin{bmatrix}a\\b\end{bmatrix}=\begin{bmatrix}1\\0\end{bmatrix}\)。若 \(\begin{bmatrix}1&-1\\3&-2\end{bmatrix}\begin{bmatrix}2a+1\\2b+1\end{bmatrix}=\begin{bmatrix}c\\d\end{bmatrix}\)，則 \(c-3d\) 之值為 ？",
                 "solution": {"brief": r"\(c-3d=-1\)",
                              "steps": [r"由第一式 \(\begin{cases}a-b=1\\3a-2b=0\end{cases}\Rightarrow a=-2,\;b=-3\)，故 \(2a+1=-3,\;2b+1=-5\)；代入得 \(\begin{bmatrix}c\\d\end{bmatrix}=\begin{bmatrix}1&-1\\3&-2\end{bmatrix}\begin{bmatrix}-3\\-5\end{bmatrix}=\begin{bmatrix}2\\1\end{bmatrix}\)，故 \(c-3d=2-3=-1\)。"]}},
            ],
            "strategy": [
                r"「矩陣相等」常與「矩陣乘法」綁在一起：**先把乘積算出來，再對應位置列出聯立方程式** 求未知數。",
                r"善用「乘特殊矩陣的效果」：左乘 \(\begin{bmatrix}0&1\\1&0\end{bmatrix}\) ＝對調兩列、右乘對角矩陣 ＝ 對各行縮放，可省去硬乘。",
                r"乘法不可交換，搬動因子時 **左乘、右乘的位置不能對調**。",
            ],
        },
        {
            "num": "考點 2", "id": "kp2", "nav": "矩陣的高次方",
            "title": r"矩陣的高次方 \(A^n\)",
            "intro": r"高次方不是把每個元素 \(n\) 次方，而是矩陣自乘 \(n\) 次。核心技巧是**降冪**——把高次化成 \(A\) 與 \(I\) 的線性組合，避免硬乘。",
            "points": [
                {"label": r"找規律（最直觀）", "lines": [
                    r"先算 \(A^2,A^3,\dots\)，觀察 【元素的週期或數列規律】 再推 \(A^n\)；",
                    r"剪移型：\(\begin{bmatrix}1&k\\0&1\end{bmatrix}^{n}=\) 【\(\begin{bmatrix}1&nk\\0&1\end{bmatrix}\)】；",
                    r"上三角型：\(\begin{bmatrix}1&2\\0&3\end{bmatrix}^{n}=\begin{bmatrix}1&3^{\,n}-1\\0&3^{\,n}\end{bmatrix}\)。"]},
                {"label": r"降冪（最有力）", "lines": [
                    r"設法湊出 【\(A^2=kI\) 或 \(A^2=pA+qI\)】，就能把任意高次降階；",
                    r"例：\(A=\begin{bmatrix}1&1\\1&-1\end{bmatrix}\Rightarrow A^2=\) 【\(2I\)】 \(\Rightarrow A^{2n}=\) 【\(2^{\,n}I\)】。"]},
                {"label": r"[[凱萊–漢米頓定理||每個方陣都「滿足自己的特徵方程式」。二階時即 \(A^2-(\mathrm{tr}A)A+(\det A)I=O\)，移項就得到右式——這是把高次方降冪的萬用起手式。]]", "lines": [
                    r"二階方陣恆滿足 \(A^2=\) 【\((\mathrm{tr}A)\,A-(\det A)\,I\)】（\(\mathrm{tr}A\)＝[[跡||主對角線（左上到右下）元素的和，\(\begin{bmatrix}a&b\\c&d\end{bmatrix}\) 的跡為 \(a+d\)。]]，\(\det A\)＝行列式值）。"]},
                {"label": r"降冪 \(\to\) 遞迴", "lines": [
                    r"由 \(A^2=pA+qI\) 兩邊乘 \(A^{n}\) 得 \(A^{n+2}=pA^{n+1}+qA^{n}\)，故 \(A^n\) 各分量都滿足 【同一條遞迴式】（\(115\) 多8 就是考這個：\(c_{n+2}=2c_{n+1}+c_n\)）。"]},
                {"label": r"旋轉矩陣", "lines": [
                    r"\([R(\theta)]^{n}=\) 【\(R(n\theta)\)】，是高次方旋轉題的萬用鑰匙（詳見考點 5）。"]},
            ],
            "misconceptions": [
                {"wrong": r"\(A^{n}\) 是把每個元素取 \(n\) 次方", "right": r"是矩陣**自乘 \(n\) 次**"},
                {"wrong": r"\((A+B)^2=A^2+2AB+B^2\)", "right": r"一般不成立（因 \(AB\neq BA\)），唯有 \(AB=BA\) 才成立"},
                {"wrong": r"高次方只能硬乘", "right": r"先找 \(A^2=kI\) 或 \(A^2=pA+qI\) 降冪最快"},
            ],
            "questions": [
                {"tag": "110 舊制 · 單選 1", "level": "★☆☆（易）", "core": "矩陣乘積（高次方）的定義",
                 "body": r"設 \(A=\begin{bmatrix}1&2\\0&3\end{bmatrix}\)，若 \(A^4=\begin{bmatrix}a&b\\c&d\end{bmatrix}\)，則 \(a+b+c+d\) 之值為下列哪一個選項？",
                 "options": ["158", "162", "166", "170", "174"],
                 "solution": {"brief": r"(2)，\(a+b+c+d=162\)",
                              "steps": [r"歸納 \(A^{n}=\begin{bmatrix}1&3^{\,n}-1\\0&3^{\,n}\end{bmatrix}\)，故 \(A^4=\begin{bmatrix}1&80\\0&81\end{bmatrix}\)，\(a+b+c+d=1+80+0+81=162\)。"]}},
                {"tag": "111 數B · 單選 5", "level": "★★☆（中）", "core": "以乘法計算高次方矩陣、係數積",
                 "body": r"設矩陣 \(A=\begin{bmatrix}1&1\\1&-1\end{bmatrix}\)，若 \(A^{7}-3A=\begin{bmatrix}a&b\\c&d\end{bmatrix}\)，則 \(a+b+c+d\) 之值為下列哪一個選項？",
                 "options": [r"\(-8\)", r"\(-5\)", "5", "8", "10"],
                 "solution": {"brief": r"(5)，\(a+b+c+d=10\)",
                              "steps": [r"\(A^2=\begin{bmatrix}2&0\\0&2\end{bmatrix}=2I\Rightarrow A^4=(2I)^2=4I\Rightarrow A^{7}=A^4A^2A=8A\)。故 \(A^{7}-3A=5A=\begin{bmatrix}5&5\\5&-5\end{bmatrix}\)，元素和 \(=10\)。"]}},
                {"tag": "115 數A · 多選 8", "level": "★★★（難）", "core": "矩陣的乘法、遞迴關係",
                 "body": r"已知 \(A=\begin{bmatrix}2&1\\1&0\end{bmatrix}\)，且對所有正整數 \(n\)，令 \(A^{n}=\begin{bmatrix}a_n&b_n\\c_n&d_n\end{bmatrix}\)。試選出正確的選項。",
                 "options": [r"\(b_n\lt c_n\)", r"\(A^2=2A+\begin{bmatrix}1&0\\0&1\end{bmatrix}\)", r"\(c_{n+2}=c_{n+1}+2c_n\)",
                             r"\(\begin{bmatrix}a_n&b_n\\c_n&d_n\end{bmatrix}\begin{bmatrix}0\\1\end{bmatrix}=\begin{bmatrix}b_{n+1}\\d_{n+1}\end{bmatrix}\)",
                             r"\(d_{2n}-a_{2n}=(d_n)^2-(a_n)^2\)"],
                 "solution": {"brief": r"(2)(5)",
                              "steps": [r"\(A^2=\begin{bmatrix}5&2\\2&1\end{bmatrix}\)。(1)✗：\(b_2=c_2=2\)。(2)○：\(2A+I=\begin{bmatrix}5&2\\2&1\end{bmatrix}=A^2\)。(3)✗：由 \(A^2=2A+I\) 得 \(A^{n+2}=2A^{n+1}+A^{n}\)，故 \(c_{n+2}=2c_{n+1}+c_n\)。(4)✗：左式 \(=\begin{bmatrix}b_n\\d_n\end{bmatrix}\neq\begin{bmatrix}b_{n+1}\\d_{n+1}\end{bmatrix}\)。(5)○：由 \(A^{2n}=A^{n}A^{n}\) 比較對應元素可得。"]}},
            ],
            "strategy": [
                r"看到高次方先別硬乘：**先算 \(A^2\)**，檢查是不是 \(kI\) 或能寫成 \(pA+qI\)（二階一定可以，用凱萊–漢米頓）。",
                r"是旋轉矩陣就直接用 \([R(\theta)]^{n}=R(n\theta)\)。",
                r"多選題常把降冪與遞迴關係 \(A^{n+2}=pA^{n+1}+qA^{n}\) 綁在一起考，先求出遞迴式再逐項驗證。",
            ],
        },
        {
            "num": "考點 3", "id": "kp3", "nav": "反方陣與解矩陣方程式",
            "title": r"反方陣與解矩陣方程式",
            "intro": r"反方陣是矩陣版的「除法」。重點有二：用二階公式快速求 \(A^{-1}\)，以及解矩陣方程時 **左乘、右乘的位置絕不能對調**。只有 \(\det A\neq0\)（可逆）的方陣才有反方陣。",
            "points": [
                {"label": r"反方陣的定義", "lines": [
                    r"\(A\)、\(B\) 同為 \(n\) 階方陣，若 \(AB=BA=I\)，則 \(B\) 是 \(A\) 的反方陣，記 【\(B=A^{-1}\)】；",
                    r"反方陣唯一，且 \((A^{-1})^{-1}=\) 【\(A\)】。"]},
                {"label": r"可逆判定（行列式）", "lines": [
                    r"二階 \(A=\begin{bmatrix}a&b\\c&d\end{bmatrix}\) 的行列式 \(\det A=\) 【\(ad-bc\)】；",
                    r"\(A\) 有反方陣 \(\Leftrightarrow\) 【\(\det A\neq0\)】，此時稱 \(A\) [[可逆||\(\det A\neq0\) 叫「可逆／非奇異」；\(\det A=0\) 叫「不可逆／奇異」，沒有反方陣。]]。"]},
                {"label": r"二階反方陣公式", "lines": [
                    r"\(A^{-1}=\) 【\(\dfrac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}\)】；",
                    r"口訣：[[主對角線對調、副對角線變號||左上 \(a\) 與右下 \(d\) 互換、右上 \(b\) 與左下 \(c\) 變號，最後整個除以行列式 \(ad-bc\)。]]，再除以行列式。"]},
                {"label": r"反方陣的性質", "lines": [
                    r"\((AB)^{-1}=\) 【\(B^{-1}A^{-1}\)】（**順序顛倒**，像穿脫衣服：後穿的先脫）；",
                    r"列運算求法：把 \([\,A\mid I\,]\) 用高斯消去化成 【\([\,I\mid A^{-1}\,]\)】，右半即為 \(A^{-1}\)。"]},
                {"label": r"解矩陣方程", "lines": [
                    r"\(AX=B\Rightarrow X=\) 【\(A^{-1}B\)】（\(A\) 在左，就左乘 \(A^{-1}\)）；",
                    r"\(XA=B\Rightarrow X=\) 【\(BA^{-1}\)】（\(A\) 在右，就右乘 \(A^{-1}\)）；關鍵：左乘、右乘的位置 【不可對調】。"]},
                {"label": r"相似矩陣求高次方", "lines": [
                    r"若 \(B=PAP^{-1}\)，則 \(B^{n}=\) 【\(PA^{n}P^{-1}\)】（中間 \(P^{-1}P=I\) 一路相消）；",
                    r"當 \(A\) 是對角矩陣時 \(A^n\) 很好算，這招能把難算的 \(B^n\) 化成好算的 \(A^n\)（好好學常考）。"]},
            ],
            "misconceptions": [
                {"wrong": r"任何方陣都有反方陣", "right": r"須 \(\det A\neq0\)（可逆）才有反方陣"},
                {"wrong": r"\((AB)^{-1}=A^{-1}B^{-1}\)", "right": r"\(=B^{-1}A^{-1}\)（順序要顛倒）"},
                {"wrong": r"\(AX=B\Rightarrow X=BA^{-1}\)", "right": r"\(X=A^{-1}B\)（\(A\) 在左就從左乘）"},
            ],
            "questions": [
                {"tag": "109 舊制 · 單選 4", "level": "★★☆（中）", "core": "單位矩陣、反方陣、矩陣的乘法與加法",
                 "body": r"令 \(I=\begin{bmatrix}1&0\\0&1\end{bmatrix}\)、\(A=\begin{bmatrix}1&1\\3&4\end{bmatrix}\)、\(B=I+A+A^{-1}\)，試選出代表 \(BA\) 的選項。",
                 "options": [r"\(\begin{bmatrix}1&0\\0&1\end{bmatrix}\)", r"\(\begin{bmatrix}6&6\\0&0\end{bmatrix}\)", r"\(\begin{bmatrix}4&-1\\-3&1\end{bmatrix}\)", r"\(\begin{bmatrix}1&1\\3&4\end{bmatrix}\)", r"\(\begin{bmatrix}6&6\\18&24\end{bmatrix}\)"],
                 "solution": {"brief": r"(5)",
                              "steps": [r"化簡 \(BA\) 可避開求反方陣：\(BA=(I+A+A^{-1})A=A+A^2+A^{-1}A=A+A^2+I\)。",
                                        r"其中 \(A^2=\begin{bmatrix}4&5\\15&19\end{bmatrix}\)，故 \(BA=\begin{bmatrix}1&1\\3&4\end{bmatrix}+\begin{bmatrix}4&5\\15&19\end{bmatrix}+\begin{bmatrix}1&0\\0&1\end{bmatrix}=\begin{bmatrix}6&6\\18&24\end{bmatrix}\)。"]}},
                {"tag": "114 數B · 單選 2", "level": "★☆☆（易）", "core": "矩陣乘法、二階反方陣",
                 "body": r"設 \(A\) 為 \(3\times2\) 階矩陣，且 \(A\begin{bmatrix}1&0\\-1&1\end{bmatrix}=\begin{bmatrix}4&-6\\-2&1\\3&5\end{bmatrix}\)。若 \(A\begin{bmatrix}1\\0\end{bmatrix}=\begin{bmatrix}a\\b\\c\end{bmatrix}\)，試問 \(a+b+c\) 之值為何？",
                 "options": ["0", "2", "4", "5", "8"],
                 "solution": {"brief": r"(4)，\(a+b+c=5\)",
                              "steps": [r"右乘 \(\begin{bmatrix}1&0\\-1&1\end{bmatrix}^{-1}=\begin{bmatrix}1&0\\1&1\end{bmatrix}\) 還原 \(A\)：\(A=\begin{bmatrix}4&-6\\-2&1\\3&5\end{bmatrix}\begin{bmatrix}1&0\\1&1\end{bmatrix}=\begin{bmatrix}-2&-6\\-1&1\\8&5\end{bmatrix}\)，",
                                        r"故 \(A\begin{bmatrix}1\\0\end{bmatrix}=\begin{bmatrix}-2\\-1\\8\end{bmatrix}\)，\(a+b+c=-2-1+8=5\)。"]}},
                {"tag": "115 數B · 單選 3", "level": "★☆☆（易）", "core": "反方陣的定義",
                 "body": r"已知實數二階方陣 \(A\) 滿足 \(A\begin{bmatrix}1\\1\end{bmatrix}=\begin{bmatrix}0\\1\end{bmatrix}\) 以及 \(A\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}1\\0\end{bmatrix}\)，試選出 \(A\) 的反方陣。",
                 "options": [r"\(\begin{bmatrix}0&1\\1&0\end{bmatrix}\)", r"\(\begin{bmatrix}1&1\\-1&1\end{bmatrix}\)", r"\(\begin{bmatrix}1&1\\1&-1\end{bmatrix}\)", r"\(\begin{bmatrix}1&\frac12\\-\frac12&1\end{bmatrix}\)", r"\(\begin{bmatrix}1&-\frac12\\\frac12&1\end{bmatrix}\)"],
                 "solution": {"brief": r"(2)",
                              "steps": [r"反方陣即把「輸入↔輸出」反過來：由條件得 \(A^{-1}\begin{bmatrix}0\\1\end{bmatrix}=\begin{bmatrix}1\\1\end{bmatrix}\)、\(A^{-1}\begin{bmatrix}1\\0\end{bmatrix}=\begin{bmatrix}1\\-1\end{bmatrix}\)。",
                                        r"\(A^{-1}\) 的兩行就是兩基底 \(\begin{bmatrix}1\\0\end{bmatrix},\begin{bmatrix}0\\1\end{bmatrix}\) 的像，故 \(A^{-1}=\begin{bmatrix}1&1\\-1&1\end{bmatrix}\)。"]}},
            ],
            "strategy": [
                r"題目給「\(A\) 作用在某些向量的結果」時，把這些向量並排成方陣 \(M\)，得 \(AM=N\)，再用 \(A=NM^{-1}\) 還原 \(A\)；若湊出 \(AM=I\)，則 \(M\) 直接就是 \(A^{-1}\)。",
                r"能用 \(A+A^2+I\) 這類化簡時，**盡量避開實際去求反方陣**，又快又不易錯。",
                r"解方程務必分清 \(AX=B\)（左乘 \(A^{-1}\)）與 \(XA=B\)（右乘 \(A^{-1}\)），位置不可對調。",
            ],
        },
        {
            "num": "考點 4", "id": "kp4", "nav": "一次聯立與高斯消去",
            "title": r"一次聯立方程式與高斯消去法",
            "intro": r"把聯立方程組翻譯成增廣矩陣、用列運算化簡，再 **判斷解的個數**。幾何上就是看三個平面怎麼相交——這是矩陣單元 **★★★ 必考核心**，數 A 幾乎年年出現。",
            "points": [
                {"label": r"增廣矩陣", "lines": [
                    r"把係數與常數項分離記成 ［ 【係數矩陣】 ｜ 【常數項】 ］（缺項補 0），稱 [[增廣矩陣||例 \(\begin{cases}x+2y+3z=10\\3x+y+z=12\\2x-y+z=5\end{cases}\) 記成 \(\left[\begin{array}{ccc|c}1&2&3&10\\3&1&1&12\\2&-1&1&5\end{array}\right]\)。]]。"]},
                {"label": r"三種列運算（解不變）", "lines": [
                    r"① 兩列互換；",
                    r"② 某列乘以 【非零】 常數；",
                    r"③ 某列加上另一列的 【倍數】。"]},
                {"label": r"高斯消去法", "lines": [
                    r"用列運算把增廣矩陣化成 [[列梯形（上三角）||化成 \(\left[\begin{array}{ccc|c}a_1&b_1&c_1&d_1\\0&b_2&c_2&d_2\\0&0&c_3&d_3\end{array}\right]\) 後，由最後一列先解出 \(z\)，再往上回代。]] 形式，再由下往上 【回代】 求 \(z,y,x\)。"]},
                {"label": r"解的判別（看列簡後的最末列）", "lines": [
                    r"出現 \([\,0\;0\;0\mid k\,],\,k\neq0\Rightarrow\) 【無解】（矛盾）；",
                    r"出現 \([\,0\;0\;0\mid 0\,]\) 且其餘相容 \(\Rightarrow\) 【無限多解】；",
                    r"三變數皆有主元 \(\Rightarrow\) 【恰有一組解】。"]},
                {"label": r"二元情形可用係數比快速判別", "lines": [
                    r"\(\begin{cases}a_1x+b_1y=c_1\\a_2x+b_2y=c_2\end{cases}\)：若 \(\dfrac{a_1}{a_2}=\dfrac{b_1}{b_2}\neq\dfrac{c_1}{c_2}\Rightarrow\) 【無解】；",
                    r"三比值全相等 \(\Rightarrow\) 【無限多解】；否則 \(\Rightarrow\) 【恰一解】。"]},
            ],
            "tables": [
                {"title": r"三平面相交關係（用法向量判別 · 取自好好學）",
                 "head": [r"三法向量", r"幾何情形", r"解"],
                 "rows": [
                     [r"皆平行", r"三平面重合", r"無限多解"],
                     [r"皆平行", r"兩面重合且平行第三面／三平面互相平行", r"無解"],
                     [r"恰兩平行", r"兩面重合且與第三面交一線", r"無限多解"],
                     [r"恰兩平行", r"兩面平行且各與第三面交一線", r"無解"],
                     [r"皆不平行", r"三平面交於一點", r"恰一解"],
                     [r"皆不平行", r"三平面交於一直線", r"無限多解"],
                     [r"皆不平行", r"兩兩交一線且三線平行", r"無解"],
                 ]},
            ],
            "misconceptions": [
                {"wrong": r"只要出現全零列就有無限多解", "right": r"要看 \([000\mid0]\)（相容→無限多解）還是 \([000\mid k],k\neq0\)（矛盾→無解）"},
                {"wrong": r"方程式個數＝未知數個數就有唯一解", "right": r"要看 **係數行列式是否為 \(0\)**"},
                {"wrong": r"化簡前就急著判斷", "right": r"必須化到列梯形、**看最末一列** 才能判別"},
            ],
            "questions": [
                {"tag": "106 舊制 · 選填 D", "level": "★★☆（中）", "core": "方程組「有解」（含無限多解）的條件",
                 "body": r"設 \(a_1,a_2,\dots,a_9\) 為等差數列且 \(k\) 為實數。若方程組 \(\begin{cases}a_1x-a_2y+2a_3z=k+1\\a_4x-a_5y+2a_6z=-k-5\\a_7x-a_8y+2a_9z=k+9\end{cases}\) 有解，則 \(k=\) ？",
                 "solution": {"brief": r"\(k=-5\)",
                              "steps": [r"因 \(\{a_n\}\) 等差，三式的係數列也成等差，故〔第1列〕\(-2\times\)〔第2列〕\(+\)〔第3列〕的係數全為 \(0\)。",
                                        r"要使方程組有解，常數項須滿足同一關係：\((k+1)-2(-k-5)+(k+9)=0\Rightarrow 4k+20=0\Rightarrow k=-5\)。"]}},
                {"tag": "111 數A · 選填 14", "level": "★★☆（中）", "core": "高斯消去法、由列簡矩陣回推",
                 "body": r"已知 \(a,b\) 為實數，且方程組 \(\begin{cases}ax+5y+12z=4\\x+ay+\frac83z=7\\3x+8y+az=1\end{cases}\) 恰有一組解，又此方程經高斯消去後，原增廣矩陣可化為 \(\begin{bmatrix}1&2&b&7\\0&b&5&-5\\0&0&b&0\end{bmatrix}\)。則 \(a=\) ？，\(b=\) ？（化為最簡分數）",
                 "solution": {"brief": r"\(a=2,\;b=\dfrac12\)",
                              "steps": [r"由列簡矩陣回推 \(\begin{cases}x+2y+bz=7\\by+5z=-5\\bz=0\end{cases}\)。恰一組解需 \(b\neq0\)，得 \(z=0,\;y=-\tfrac5b,\;x=7+\tfrac{10}{b}\)，",
                                        r"再代回原方程第一、二式聯立，解得 \(a=2,\;b=\tfrac12\)。"]}},
                {"tag": "112 數A · 選填 13", "level": "★☆☆（易）", "core": "三元一次聯立方程式",
                 "body": r"某飲料店推出果汁、奶茶、咖啡三種飲料，前 3 天各飲料銷售量（杯）與收入（元）如下表。已知每種飲料每天售價皆相同，則咖啡每杯售價為 ？ 元。",
                 "table": {"head": [r"　", r"果汁", r"奶茶", r"咖啡", r"收入"],
                           "rows": [[r"第1天", "60", "80", "50", "12900"],
                                    [r"第2天", "30", "40", "30", "6850"],
                                    [r"第3天", "50", "60", "70", "10800"]]},
                 "solution": {"brief": r"咖啡每杯 80 元",
                              "steps": [r"設三飲料每杯 \(x,y,z\) 元，列 \(\begin{cases}60x+80y+50z=12900\\30x+40y+30z=6850\\50x+60y+70z=10800\end{cases}\)。",
                                        r"取〔第1式〕\(-2\times\)〔第2式〕可一次消去 \(x,y\)：\(-z=-80\Rightarrow z=80\)。"]}},
                {"tag": "113 數A · 選填 13", "level": "★★☆（中）", "core": "三元一次聯立（比例）",
                 "body": r"某站賣甲、乙、丙三型手機，每支利潤分別為 100、400、240 元。上半年三型共賣出 \(A,B,C\) 支，平均每支利潤 260 元；且甲、乙兩型共 \(A+B\) 支的平均每支利潤為 280 元。則三型數量比 \(A:B:C=\) ？（化為最簡整數比）",
                 "solution": {"brief": r"\(A:B:C=2:3:5\)",
                              "steps": [r"由 \(\begin{cases}100A+400B+240C=260(A+B+C)\\100A+400B=280(A+B)\end{cases}\) 化簡得 \(\begin{cases}8A-7B+C=0\\3A=2B\end{cases}\)，",
                                        r"令 \(A=2t\) 得 \(B=3t,\;C=5t\)，故 \(A:B:C=2:3:5\)。"]}},
                {"tag": "113 數A · 多選 11", "level": "★★★（難 · 跨單元：矩陣 × 機率）", "core": "二元方程組解的判別、古典機率、條件機率",
                 "body": r"考慮二元一次方程組 \(\begin{cases}ax+6y=6\\x+by=1\end{cases}\)，係數 \(a,b\) 由投擲一顆公正骰子與一枚均勻硬幣決定：\(a\) 為骰子點數；硬幣正面 \(b=1\)、反面 \(b=2\)。試選出正確的選項。",
                 "options": [r"擲出 \(a=b\) 的機率為 \(\frac13\)", r"方程組無解的機率為 \(\frac{1}{12}\)", r"恰有一組解的機率為 \(\frac56\)", r"硬幣反面且方程組有解的機率為 \(\frac12\)", r"在硬幣反面且有解的條件下，\(a\) 值符合某條件的機率為 \(\frac25\)"],
                 "solution": {"brief": r"(2)(3)",
                              "steps": [r"樣本空間 \(n(S)=6\times2=12\)。由係數比 \(\tfrac{a}{1}=\tfrac{6}{b}\) 時兩直線平行或重合。",
                                        r"無解（平行）發生於 \((a,b)=(3,2)\)，機率 \(\tfrac1{12}\)；無限多解（重合）發生於 \((a,b)=(6,1)\)，機率 \(\tfrac1{12}\)。",
                                        r"故「恰一組解」機率 \(=1-\tfrac1{12}-\tfrac1{12}=\tfrac56\)。(1)(4)(5) 經計算數值不符。"]}},
                {"tag": "115 數A · 單選 5", "level": "★★★（難 · 跨單元：矩陣 × 空間）", "core": "矩陣乘法、高斯消去（解的存在性）",
                 "body": r"已知實數三階方陣 \(A\) 滿足 \(A\begin{bmatrix}1\\1\\0\end{bmatrix}=\begin{bmatrix}0\\-1\\1\end{bmatrix}\)，\(A\begin{bmatrix}1\\-1\\1\end{bmatrix}=\begin{bmatrix}1\\1\\0\end{bmatrix}\)，\(A\begin{bmatrix}1\\0\\-1\end{bmatrix}=\begin{bmatrix}0\\0\\0\end{bmatrix}\)。試問有多少個行向量 \(v=\begin{bmatrix}v_1\\v_2\\v_3\end{bmatrix}\) 滿足 \(Av=\begin{bmatrix}1\\0\\1\end{bmatrix}\) 且 \(v\) 垂直於 \(\begin{bmatrix}0\\1\\0\end{bmatrix}\)？",
                 "options": [r"1 個", r"2 個", r"3 個", r"0 個", r"無窮多個"],
                 "solution": {"brief": r"(5) 無窮多個",
                              "steps": [r"由 \(A\begin{bmatrix}1\\0\\-1\end{bmatrix}=\mathbf0\) 知 \(A\) 不可逆（核空間含 \(\begin{bmatrix}1\\0\\-1\end{bmatrix}\)）。",
                                        r"又 \(\begin{bmatrix}1\\0\\1\end{bmatrix}=A\begin{bmatrix}1\\1\\0\end{bmatrix}+A\begin{bmatrix}1\\-1\\1\end{bmatrix}=A\begin{bmatrix}2\\0\\1\end{bmatrix}\)，得特解 \(v_0=\begin{bmatrix}2\\0\\1\end{bmatrix}\)（其 \(v_2=0\) 符合垂直條件）。",
                                        r"通解 \(v=v_0+t\begin{bmatrix}1\\0\\-1\end{bmatrix}\) 第二分量恆為 \(0\)，永遠滿足垂直條件，故有無窮多個。"]}},
                {"tag": "114 數A · 選填 14", "level": "★★★（難 · 跨單元：矩陣 × 空間）", "core": "點到平面距離化為三元一次聯立",
                 "body": r"坐標空間中，已知點 \(A(a,b,c)\)，其中 \(a,b,c\) 皆為小於 \(0\) 的實數。若 \(A\) 到三平面 \(E_1:4y+3z=2\)、\(E_2:3y+4z=-5\)、\(E_3:x+2y+2z=-2\) 的距離都是 \(6\)，則 \(a+b+c=\) ？",
                 "solution": {"brief": r"\(a+b+c=-11\)（\(a=-2,\;b=-1,\;c=-8\)）",
                              "steps": [r"\(E_1,E_2\) 不含 \(x\)，法向量 \((0,4,3)\)、\((0,3,4)\) 長度皆為 \(5\)。距離皆 \(6\)、且 \(b,c\lt0\)，去絕對值得 \(\begin{cases}4b+3c=-28\\3b+4c=-35\end{cases}\Rightarrow b=-1,\;c=-8\)。",
                                        r"再用 \(E_3:x+2y+2z=-2\)（法向量 \((1,2,2)\) 長度 \(3\)）：\(\dfrac{|a+2b+2c+2|}{3}=6\Rightarrow|a-16|=18\)，因 \(a\lt0\) 取 \(a=-2\)。",
                                        r"故 \(a+b+c=-2-1-8=-11\)。**關鍵**：先挑「不含 \(x\) 的兩式」解出 \(b,c\)，再回代第三式——這正是高斯消去「由簡到繁」的精神。"]}},
            ],
            "strategy": [
                r"係數成等差／等比的方程組，常可用 **列相減** 一次消去（\(106\) 選D、\(112\) 選13 都是這招）。",
                r"判別解的個數：先把增廣矩陣化到 **列梯形** 再看最末一列；二元可直接用係數比 \(\tfrac{a_1}{a_2}=\tfrac{b_1}{b_2}\) 快速判斷。",
                r"看到「點到多個平面距離」就把每個距離寫成一條一次方程式，化為聯立用矩陣解（\(114\) 選14、\(115\) 單5）。",
            ],
        },
        {
            "num": "考點 5", "id": "kp5", "nav": "平面線性變換",
            "title": r"平面線性變換（旋轉、鏡射、伸縮、推移）",
            "intro": r"用矩陣去「搬動」平面上的點。四種變換各有固定矩陣形式，最常考的結論是 **變換後面積 ＝ 原面積 \(\times|\det M|\)**。是矩陣單元 **★★★ 必考核心**，常與向量、三角整合成混合題組。",
            "points": [
                {"label": r"線性變換", "lines": [
                    r"點 \(P(x,y)\to P'(x',y')\)：\(\begin{bmatrix}x'\\y'\end{bmatrix}=\) 【\(M\begin{bmatrix}x\\y\end{bmatrix}\)】，\(M\) 為 \(2\times2\) 變換矩陣。"]},
                {"label": r"旋轉矩陣（繞原點逆時針 \(\theta\)）", "lines": [
                    r"\(R(\theta)=\) 【\(\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}\)】；",
                    r"\([R(\theta)]^{n}=\) 【\(R(n\theta)\)】，\(\det R=1\)（恆可逆），面積 【不變】。"]},
                {"label": r"鏡射矩陣（對與 \(x\) 軸夾 \(\theta\) 的直線）", "lines": [
                    r"\(\begin{bmatrix}\cos2\theta&\sin2\theta\\\sin2\theta&-\cos2\theta\end{bmatrix}\)，\(\det=\) 【\(-1\)】，面積 【不變】；",
                    r"常用：對 \(x\) 軸 \(\begin{bmatrix}1&0\\0&-1\end{bmatrix}\)、對 \(y=x\) \(\begin{bmatrix}0&1\\1&0\end{bmatrix}\)。"]},
                {"label": r"伸縮與推移（剪移）", "lines": [
                    r"伸縮 \(\begin{bmatrix}h&0\\0&k\end{bmatrix}\)，面積變 【\(|hk|\)】 倍；反矩陣為 \(\begin{bmatrix}\frac1h&0\\0&\frac1k\end{bmatrix}\)；",
                    r"推移 \(\begin{bmatrix}1&k\\0&1\end{bmatrix}\) 或 \(\begin{bmatrix}1&0\\k&1\end{bmatrix}\)，\(\det=1\)，面積 【不變】。"]},
                {"label": r"面積黃金律", "lines": [
                    r"圖形經 \(M\) 變換後，面積 ＝ 【原面積 \(\times|\det M|\)】（[[務必取絕對值||\(\det M\) 可能為負（例如鏡射 \(\det=-1\)），但面積恆為正，所以要取 \(|\det M|\)。]]）。"]},
            ],
            "misconceptions": [
                {"wrong": r"面積變化倍率是 \(\det M\)", "right": r"是 \(|\det M|\)（要取絕對值）"},
                {"wrong": r"旋轉與鏡射可以交換", "right": r"一般 **不可交換**（\(RS\neq SR\)）"},
                {"wrong": r"旋轉可能不可逆", "right": r"旋轉 \(\det R=1\) 恆可逆；鏡射 \(\det=-1\) 也可逆"},
            ],
            "questions": [
                {"tag": "110 舊制 · 多選 8", "level": "★★★（難 · 跨單元：矩陣 × 向量 × 圓 × 三角）", "core": "圓上弦長與旋轉（旋轉矩陣 \\(R(60^\\circ)\\)）",
                 "body": r"如圖，\(L\) 為坐標平面上通過原點 \(O\) 的直線，\(\Gamma\) 為以 \(O\) 為圓心的圓，且 \(L\) 與 \(\Gamma\) 交於一點 \(A(3,4)\)。已知 \(B,C\) 為 \(\Gamma\) 上相異兩點且滿足 \(\overrightarrow{BC}=\overrightarrow{OA}\)。試選出正確的選項。",
                 "options": [r"\(L\) 與 \(\Gamma\) 的另一個交點為 \((-4,-3)\)", r"直線 \(BC\) 的斜率為 \(\dfrac34\)", r"\(\angle AOC=60^\circ\)", r"\(\triangle ABC\) 的面積為 \(\dfrac{25\sqrt3}{2}\)", r"\(B\) 與 \(C\) 在同一象限內"],
                 "solution": {"brief": r"(3)(5)",
                              "steps": [r"\(\Gamma:\,x^2+y^2=25\)（半徑 \(|OA|=5\)）。\(\overrightarrow{BC}=\overrightarrow{OA}\Rightarrow BC\parallel OA\) 且 \(|BC|=5=\) 半徑，故弦 \(BC\) 的圓心角 \(\angle BOC=60^\circ\)，亦即 \(C\) 為 \(B\) 繞 \(O\) 旋轉 \(60^\circ\) 的像（可用旋轉矩陣 \(R(60^\circ)\) 表示）。",
                                        r"(1)✗：\(L\) 過 \(O,A(3,4)\)，另一交點是對徑點 \((-3,-4)\)，非 \((-4,-3)\)。(2)✗：\(BC\parallel OA=(3,4)\)，斜率為 \(\tfrac43\) 而非 \(\tfrac34\)。",
                                        r"(3)○、(5)○：由旋轉關係可得 \(\angle AOC=60^\circ\)，且 \(B,C\) 落在同一象限；(4)✗（面積非此值）。**官方答案 (3)(5)**。"]}},
                {"tag": "112 數A · 多選 11", "level": "★★☆（中）", "core": "旋轉矩陣、鏡射矩陣、以乘法判斷性質",
                 "body": r"坐標平面上，設 \(A,B\) 分別為以原點為中心、順時針與逆時針旋轉 \(90^\circ\) 的旋轉矩陣；\(C,D\) 分別為以直線 \(x=y\)、\(x=-y\) 為鏡射軸的鏡射矩陣。試選出正確的選項。",
                 "options": [r"\(A,C\) 將 \((1,0)\) 映射到同一點", r"\(A=-B\)", r"\(C=D^{-1}\)", r"\(AB=CD\)", r"\(AC=BD\)"],
                 "solution": {"brief": r"(2)(5)",
                              "steps": [r"寫出 \(A=\begin{bmatrix}0&1\\-1&0\end{bmatrix}\)、\(B=\begin{bmatrix}0&-1\\1&0\end{bmatrix}\)、\(C=\begin{bmatrix}0&1\\1&0\end{bmatrix}\)、\(D=\begin{bmatrix}0&-1\\-1&0\end{bmatrix}\)。",
                                        r"(2) \(-B=A\) ○；(5) \(AC=\begin{bmatrix}1&0\\0&-1\end{bmatrix}=BD\) ○；其餘逐一檢驗皆不成立。"]}},
                {"tag": "113 數A · 多選 12", "level": "★★☆（中）", "core": "平面線性變換、面積與行列式、可逆",
                 "body": r"坐標平面上給定三點 \(A(1,0)\)、\(B(0,1)\)、\(C(-1,0)\)，令 \(\Gamma\) 為 \(\triangle ABC\) 經矩陣 \(T=\begin{bmatrix}3&0\\a&1\end{bmatrix}\) 變換後的圖形，\(a\) 為實數。試選出正確的選項。",
                 "options": [r"若 \(a=0\)，則 \(\Gamma\) 為等腰直角三角形", r"\(\triangle ABC\) 邊上至少有兩點經 \(T\) 變換後位置不變", r"\(\Gamma\) 必有部分落在第四象限", r"平面上找得到圖形 \(\Omega\)，使其經 \(T\) 變換後恰為 \(\triangle ABC\)", r"\(\Gamma\) 的面積為定值"],
                 "solution": {"brief": r"(2)(4)(5)",
                              "steps": [r"\(\det T=3\neq0\) 故 \(T\) 可逆，(4) ○。三頂點變換後為 \(A'(3,a)\)、\(B'(0,1)\)、\(C'(-3,-a)\)，邊上有不動點，(2) ○。",
                                        r"面積 \(=\triangle ABC\times|\det T|=(\tfrac12\cdot2\cdot1)\times3=3\) 為定值，(5) ○。"]}},
                {"tag": "114 數A · 混合題 18–20（題組）", "level": "★★★（中～難）", "core": "旋轉矩陣、\\([R(\\theta)]^{n}=R(n\\theta)\\)、直線交點",
                 "body": r"已知 \(A,B\) 皆為以原點 \(O\) 為中心、逆時針旋轉一銳角的旋轉矩陣，且滿足 \(A^2=B^3=\begin{bmatrix}0&c\\1&d\end{bmatrix}\)，\(c,d\) 為實數。情境中以點 \(P(1,1)\) 經旋轉得到 \(Q,R\)。",
                 "subqs": [
                     {"label": r"第 18 題（單選，3 分）：試問 \(c\) 之值為何？",
                      "solution": {"brief": r"\(c=-1\)",
                                   "steps": [r"旋轉矩陣形如 \(\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}\)，與 \(\begin{bmatrix}0&c\\1&d\end{bmatrix}\) 比對得 \(\cos\theta=0,\sin\theta=1\)（即旋轉 \(90^\circ\)），故 \(c=-\sin\theta=-1,\;d=\cos\theta=0\)。"]}},
                     {"label": r"第 19 題（非選，6 分）：求點 \(Q\) 的坐標，及 \(\overrightarrow{OR}\) 與向量 \((1,0)\) 的夾角。",
                      "solution": {"brief": r"\(Q=(-\sqrt2,\,0)\)；夾角 \(60^\circ\)",
                                   "steps": [r"由 \(A^2=R(90^\circ)\) 知 \(A=R(45^\circ)\)；由 \(B^3=R(90^\circ)\) 知 \(B=R(30^\circ)\)。",
                                             r"再用 \([R(\theta)]^{n}=R(n\theta)\) 對 \(P(1,1)\) 作旋轉並求向量夾角。"]}},
                     {"label": r"第 20 題（非選）：設 \(L\) 過 \(P\) 且平行 \(OQ\)，\(S\) 為 \(L\) 與直線 \(OR\) 的交點，求 \(\angle OSP\) 及 \(S\) 坐標。",
                      "solution": {"brief": r"\(\angle OSP=60^\circ\)；\(S=\left(-\tfrac{\sqrt3}{3},\,1\right)\)",
                                   "steps": [r"\(OQ\) 沿 \(x\) 軸方向，故 \(L:\,y=1\)；直線 \(OR:\,y=\sqrt3\,x\)，兩式聯立解得交點 \(S\)，並由斜率求 \(\angle OSP\)。"]}},
                 ]},
            ],
            "strategy": [
                r"判性質的多選題：先把每個變換 **寫成具體矩陣**，再逐一檢驗等式——比抽象推論可靠（\(112\) 多11）。",
                r"面積題只要算 \(|\det M|\) 乘原面積，**不必畫圖**（\(113\) 多12）。",
                r"旋轉高次方一律 \([R(\theta)]^{n}=R(n\theta)\)；旋轉＋鏡射記得一般不可交換、且 \(\det\) 一正一負。",
            ],
        },
    ],

    "part2": {
        "count": "13", "note": "難度略高於學測，著重觀念整合與推理 · 建議自行限時 50 分鐘作答後再對照詳解",
        "groups": [
            {"title": "一、單選題", "questions": [
                {"tag": "練習 1", "level": "★★☆", "core": "高次方、降冪（凱萊–漢米頓）",
                 "body": r"設 \(A=\begin{bmatrix}3&-1\\2&0\end{bmatrix}\)。若存在實數 \(p,q\) 使 \(A^2=pA+qI\)，則數對 \((p,q)=\) ？",
                 "options": [r"\((3,-2)\)", r"\((3,2)\)", r"\((-3,2)\)", r"\((2,-3)\)", r"\((1,-6)\)"],
                 "solution": {"brief": "(1)", "brief_label": "答",
                              "steps": [r"由凱萊–漢米頓，二階方陣滿足 \(A^2=(\mathrm{tr}A)A-(\det A)I\)。此處 \(\mathrm{tr}A=3\)、\(\det A=0-(-2)=2\)，故 \(A^2=3A-2I\)，\((p,q)=(3,-2)\)。"]}},
                {"tag": "練習 2", "level": "★★☆", "core": "旋轉矩陣的週期",
                 "body": r"設 \(R\) 為以原點為中心、逆時針旋轉 \(24^\circ\) 的旋轉矩陣，則使 \(R^{n}=I\) 的最小正整數 \(n\) 為？",
                 "options": ["10", "12", "15", "18", "24"],
                 "solution": {"brief": "(3)", "brief_label": "答",
                              "steps": [r"\(R^{n}=R(24^\circ n)=I\Leftrightarrow 24n=360m\)，最小正整數 \(n=\dfrac{360}{\gcd(24,360)}=\dfrac{360}{24}=15\)。"]}},
                {"tag": "練習 3", "level": "★★☆", "core": "解矩陣方程、反方陣",
                 "body": r"設 \(A=\begin{bmatrix}1&2\\1&3\end{bmatrix}\)，且二階方陣 \(B\) 滿足 \(AB=\begin{bmatrix}5&1\\8&2\end{bmatrix}\)，則 \(B=\) ？",
                 "options": [r"\(\begin{bmatrix}-1&-1\\3&1\end{bmatrix}\)", r"\(\begin{bmatrix}1&1\\2&0\end{bmatrix}\)", r"\(\begin{bmatrix}-1&1\\3&0\end{bmatrix}\)", r"\(\begin{bmatrix}2&1\\1&1\end{bmatrix}\)", r"\(\begin{bmatrix}3&1\\1&0\end{bmatrix}\)"],
                 "solution": {"brief": "(1)", "brief_label": "答",
                              "steps": [r"\(\det A=1\)，\(A^{-1}=\begin{bmatrix}3&-2\\-1&1\end{bmatrix}\)，故 \(B=A^{-1}\begin{bmatrix}5&1\\8&2\end{bmatrix}=\begin{bmatrix}-1&-1\\3&1\end{bmatrix}\)。"]}},
                {"tag": "練習 4", "level": "★★☆", "core": "線性變換與面積（行列式）",
                 "body": r"坐標平面上頂點為 \((0,0),(1,0),(1,1),(0,1)\) 的單位正方形，經矩陣 \(M=\begin{bmatrix}2&1\\1&3\end{bmatrix}\) 變換後成為一平行四邊形，其面積為？",
                 "options": ["4", "5", "6", "7", "8"],
                 "solution": {"brief": "(2)", "brief_label": "答",
                              "steps": [r"面積 \(=|\det M|\times(\text{原面積})=|2\cdot3-1\cdot1|\times1=5\)。"]}},
                {"tag": "練習 5", "level": "★★★", "core": "聯立方程組解的判別（行列式）",
                 "body": r"設實數 \(a\) 使方程組 \(\begin{cases}x+2y-z=1\\2x-y+3z=2\\x-3y+az=1\end{cases}\) 不恰有一組解，則 \(a=\) ？",
                 "options": ["1", "2", "3", "4", "5"],
                 "solution": {"brief": "(4)", "brief_label": "答",
                              "steps": [r"「不恰有一組解」\(\Leftrightarrow\) 係數行列式為 \(0\)。\(\det\begin{bmatrix}1&2&-1\\2&-1&3\\1&-3&a\end{bmatrix}=-5a+20=0\Rightarrow a=4\)。"]}},
            ]},
            {"title": "二、多選題", "questions": [
                {"tag": "練習 6", "level": "★★★", "core": "矩陣運算的性質",
                 "body": r"設 \(A,B\) 均為二階方陣，下列敘述何者 **恆成立**？",
                 "options": [r"\((A+B)^2=A^2+2AB+B^2\)", r"若 \(A^2=O\)，則 \(A=O\)", r"\(\det(AB)=\det(A)\det(B)\)", r"若 \(AB=I_2\)，則 \(BA=I_2\)", r"若 \(AB=AC\) 且 \(A\neq O\)，則 \(B=C\)"],
                 "solution": {"brief": "(3)(4)", "brief_label": "答",
                              "steps": [r"(1) 因 \(AB\neq BA\) 一般不成立；(2) 反例 \(A=\begin{bmatrix}0&1\\0&0\end{bmatrix}\)，\(A^2=O\) 但 \(A\neq O\)；(5) 須 \(A\) 可逆才成立。(3)(4) 為方陣的基本定理。"]}},
                {"tag": "練習 7", "level": "★★★", "core": "旋轉與鏡射矩陣",
                 "body": r"設 \(R\) 為逆時針旋轉 \(\theta\) 的旋轉矩陣，\(S\) 為以 \(x\) 軸為鏡射軸的鏡射矩陣。下列何者正確？",
                 "options": [r"\(RS=SR\)", r"\(S^2=I\)", r"\(SRS=R^{-1}\)", r"\(\det(RS)=1\)", r"對任意 \(\theta\)，\(R\) 皆有反方陣"],
                 "solution": {"brief": "(2)(3)(5)", "brief_label": "答",
                              "steps": [r"\(S=\begin{bmatrix}1&0\\0&-1\end{bmatrix}\)，\(S^2=I\)；\(SRS=R(-\theta)=R^{-1}\)；旋轉 \(\det R=1\neq0\) 恆可逆。(1) 旋轉與鏡射一般不可交換；(4) \(\det(RS)=1\cdot(-1)=-1\)。"]}},
                {"tag": "練習 8", "level": "★★★", "core": "高斯消去、三平面的幾何意義",
                 "body": r"考慮方程組 \(\begin{cases}x+y+z=1\\x+2y+3z=k\\2x+3y+4z=3\end{cases}\)（\(k\) 為實數）。下列何者正確？",
                 "options": [r"當 \(k=2\) 時，有無限多組解", r"當 \(k\neq2\) 時，方程組無解", r"不論 \(k\) 為何值，都不會恰有一組解", r"三平面恆交於一點", r"當 \(k=2\) 時，三平面交於一直線"],
                 "solution": {"brief": "(1)(2)(3)(5)", "brief_label": "答",
                              "steps": [r"因〔第3式〕=〔第1式〕+〔第2式〕（左側），係數行列式為 \(0\)，故永不恰有一組解。",
                                        r"常數需滿足 \(1+k=3\) 即 \(k=2\) 才相容：\(k=2\) 時剩兩獨立方程式 → 無限多解，解集為一直線；\(k\neq2\) 時矛盾 → 無解。(4) 錯。"]}},
            ]},
            {"title": "三、選填題", "questions": [
                {"tag": "練習 9", "level": "★★☆", "core": "矩陣相等與聯立",
                 "body": r"設二階方陣 \(M=\begin{bmatrix}a&b\\c&d\end{bmatrix}\) 滿足 \(M\begin{bmatrix}1\\1\end{bmatrix}=\begin{bmatrix}3\\7\end{bmatrix}\) 且 \(M\begin{bmatrix}1\\-1\end{bmatrix}=\begin{bmatrix}1\\1\end{bmatrix}\)，則 \(a+b+c+d=\) ？",
                 "solution": {"brief": "10", "brief_label": "答",
                              "steps": [r"\(a+b=3,\;a-b=1\Rightarrow a=2,b=1\)；\(c+d=7,\;c-d=1\Rightarrow c=4,d=3\)。故 \(a+b+c+d=10\)。"]}},
                {"tag": "練習 10", "level": "★★☆", "core": "高次方（剪移矩陣）",
                 "body": r"設 \(A=\begin{bmatrix}1&1\\0&1\end{bmatrix}\)，則 \(A+A^2+A^3+\cdots+A^{10}\) 之所有元素總和為 ？",
                 "solution": {"brief": "75", "brief_label": "答",
                              "steps": [r"\(A^{k}=\begin{bmatrix}1&k\\0&1\end{bmatrix}\)，\(\displaystyle\sum_{k=1}^{10}A^{k}=\begin{bmatrix}10&55\\0&10\end{bmatrix}\)，元素總和 \(=10+55+0+10=75\)。"]}},
                {"tag": "練習 11", "level": "★★★", "core": "旋轉矩陣與反方陣",
                 "body": r"設 \(A=\begin{bmatrix}\cos40^\circ&-\sin40^\circ\\\sin40^\circ&\cos40^\circ\end{bmatrix}\)，則使 \(A^{n}=A^{-1}\) 成立的最小正整數 \(n=\) ？",
                 "solution": {"brief": "8", "brief_label": "答",
                              "steps": [r"\(A^{n}=R(40^\circ n)\)，\(A^{-1}=R(-40^\circ)=R(320^\circ)\)。需 \(40n=320+360k\)（\(k\ge0\)），即 \(n=8+9k\)，最小正整數 \(n=8\)。"]}},
            ]},
            {"title": "四、非選擇題（須寫出計算過程）", "questions": [
                {"tag": "練習 12", "level": "★★★", "core": "含參數的三元一次方程組、高斯消去",
                 "body": r"設 \(a\) 為實數，考慮方程組 \(\begin{cases}x+y+az=1\\x+ay+z=1\\ax+y+z=1\end{cases}\)。(1) 以 \(a\) 表示係數矩陣的行列式，並求使方程組「不恰有一組解」的所有 \(a\) 值。(2) 對每一個 \(a\) 值，分別判別為「無解」或「無限多組解」。",
                 "solution": {"brief": r"\(a=1\) 或 \(a=-2\)", "brief_label": "答",
                              "steps": [r"行列式 \(\det\begin{bmatrix}1&1&a\\1&a&1\\a&1&1\end{bmatrix}=-(a-1)^2(a+2)\)。令其為 \(0\) 得 \(a=1\) 或 \(a=-2\)（不恰有一組解）。",
                                        r"\(a=1\)：三式同為 \(x+y+z=1\)，**無限多組解**；\(a=-2\)：三式相加得 \(0=3\) 矛盾，**無解**。"]}},
                {"tag": "練習 13", "level": "★★★", "core": "旋轉矩陣、矩陣冪次與幾何",
                 "body": r"設 \(A\) 為以原點為中心、逆時針旋轉 \(\theta\)（\(0\lt\theta\lt\pi\)）的旋轉矩陣，且 \(A\begin{bmatrix}2\\0\end{bmatrix}=\begin{bmatrix}1\\\sqrt3\end{bmatrix}\)。(1) 求 \(\theta\)。(2) 求 \(A^2\begin{bmatrix}1\\0\end{bmatrix}\)。(3) 說明 \(A^6=I\)，並求 \(I+A+A^2+\cdots+A^5\)。",
                 "solution": {"brief": r"\(\theta=60^\circ\)；\(A^6=I\)，和為零矩陣", "brief_label": "答",
                              "steps": [r"(1) \((2,0)\) 長度 2、輻角 \(0^\circ\)；\((1,\sqrt3)\) 長度 2、輻角 \(60^\circ\)，故 \(\theta=60^\circ\)。",
                                        r"(2) \(A^2=R(120^\circ)\)，\(A^2\begin{bmatrix}1\\0\end{bmatrix}=\begin{bmatrix}\cos120^\circ\\\sin120^\circ\end{bmatrix}=\begin{bmatrix}-\frac12\\\frac{\sqrt3}{2}\end{bmatrix}\)。",
                                        r"(3) \(A=R(60^\circ)\Rightarrow A^6=R(360^\circ)=I\)。\(\sum_{k=0}^{5}R(60^\circ k)\) 因 \(\sum\cos(60^\circ k)=\sum\sin(60^\circ k)=0\)，故為零矩陣 \(\begin{bmatrix}0&0\\0&0\end{bmatrix}\)。"]}},
            ]},
        ],
    },

    "part3": {
        "ref_table": [
            {"k": "乘法可乘條件", "v": r"\(A_{m\times n}B_{n\times p}=C_{m\times p}\)（前行數＝後列數）"},
            {"k": "係數積行列式", "v": r"\(\det(kA)=k^{\,n}\det(A)\)（\(n\) 階方陣）"},
            {"k": "高次方降冪", "v": r"找 \(A^2=kI\) 或 \(A^2=pA+qI\)；二階用 \(A^2=(\mathrm{tr}A)A-(\det A)I\)"},
            {"k": "二階反方陣", "v": r"\(A^{-1}=\dfrac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}\)，\(\det A\neq0\) 才可逆"},
            {"k": "反方陣性質", "v": r"\((AB)^{-1}=B^{-1}A^{-1}\)；\((A^{-1})^{-1}=A\)；列運算 \([\,A\mid I\,]\to[\,I\mid A^{-1}\,]\)"},
            {"k": "解矩陣方程", "v": r"\(AX=B\Rightarrow X=A^{-1}B\)；\(XA=B\Rightarrow X=BA^{-1}\)"},
            {"k": "相似求高次方", "v": r"\(B=PAP^{-1}\Rightarrow B^{n}=PA^{n}P^{-1}\)"},
            {"k": "解的判別", "v": r"\([000\mid k],k\neq0\) 無解；\([000\mid0]\) 無限多解；皆有主元 唯一解"},
            {"k": "三平面（法向量）", "v": r"皆不平行→交一點(唯一)；交一線/兩兩交線(無限多/無)；依法向量平行情形判別"},
            {"k": "旋轉矩陣", "v": r"\(R(\theta)=\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}\)，\([R(\theta)]^{n}=R(n\theta)\)，面積不變"},
            {"k": "鏡射矩陣", "v": r"\(\begin{bmatrix}\cos2\theta&\sin2\theta\\\sin2\theta&-\cos2\theta\end{bmatrix}\)，\(\det=-1\)，面積不變"},
            {"k": "伸縮 / 推移", "v": r"伸縮 \(\begin{bmatrix}h&0\\0&k\end{bmatrix}\) 面積變 \(|hk|\) 倍；推移 \(\det=1\) 面積不變"},
            {"k": "面積黃金律", "v": r"變換後面積 ＝ 原面積 \(\times|\det M|\)"},
        ],
        "checklist": [
            r"\(a_{ij}\) 是第 \(i\) 列第 \(j\) 行（列在前）。",
            r"矩陣乘法 **不交換**：一般 \(AB\neq BA\)。",
            r"\(AB=O\) **不一定** \(A=O\) 或 \(B=O\)（有零因子）。",
            r"\(AB=AC\) **不一定** \(B=C\)（須 \(A\) 可逆）。",
            r"\((A+B)^2=A^2+AB+BA+B^2\)，**只有** \(AB=BA\) 才等於 \(A^2+2AB+B^2\)。",
            r"\(A^{n}\) 是矩陣自乘 \(n\) 次，**不是**每個元素 \(n\) 次方。",
            r"只有 \(\det A\neq0\) 才有反方陣。",
            r"\((AB)^{-1}=B^{-1}A^{-1}\)（順序顛倒），別寫成 \(A^{-1}B^{-1}\)。",
            r"解方程左乘、右乘 **不可對調**。",
            r"全零列要分清 \([000\mid0]\)（無限多解）與 \([000\mid k]\)（無解）。",
            r"面積倍率是 \(|\det M|\)，要取 **絕對值**。",
            r"旋轉與鏡射一般 **不可交換**。",
        ],
    },
}
